{% set version = "1.3.1" %}

package:
  name: setproctitle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/setproctitle/setproctitle-{{ version }}.tar.gz
  sha256: 3d134c2effeb945e8227f7d3d24ea8ad49c03c87ac91a8d67bf967730fa9daba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - setproctitle

about:
  home: http://code.google.com/p/py-setproctitle/
  license: BSD 3-clause
  license_file: COPYRIGHT
  license_family: BSD
  summary: A library to allow customization of the process title.

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
    - scopatz
